### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by xuexue49** [anlen123/nonebot_plugin_abbrreply#1]
import on_command 但是下面用了 on_startswith

**Comment by anlen123** [comment]
谢谢使用，好的。

**Comment by zhzRedstone** [comment]
我也是。log如下
```
07-18 08:27:56 [ERROR] nonebot | Failed to import "nonebot_plugin_abbrreply"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 17, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/nonebot2/YanXiBot/./bot.py", line 25, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1065, in load_from_toml
    return load_all_plugins(set(plugins), set(plugin_dirs))
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1007, in load_all_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    return importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/nonebot_plugin_abbrreply/__init__.py", line 23, in <module>
    sx = on_startswith(cmd="sx", aliases={"缩写"})
TypeError: on_startswith() missing 1 required positional argument: 'msg'

```

**Comment by Harrison-LUO** [comment]
同样报错：
应该在__init__.py文件中第二行
`from nonebot import on_startswith`
改为
`from nonebot import on_command`
同时第23行
`sx = on_startswith(cmd="sx", aliases={"缩写"})`
改为
`sx = on_command(cmd="sx", aliases={"缩写"})`

这样以后运行正常不报错

**Comment by anlen123** [comment]
之前就是on_command，忘记修改参数了，现在改为了on_regex了，用on_command不太好。
